/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "math_operations.h"

int *
square_1_svc(math_input *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	printf("square(%d) is called\n", argp->num);
	result = argp->num * argp->num;

	return &result;
}

double *
square_root_1_svc(math_input *argp, struct svc_req *rqstp)
{
	static double  result;

	/*
	 * insert server code here
	 */
	int l = 0, r = argp->num;
	
	while(1) {
		int mid = l + (r-l)/2;

		if(mid*mid == argp->num){
			result = mid;
			break;
		}
		else if(mid*mid > argp->num){
			r = mid-1;
		}
		else{
			l = mid+1;
		}
	}

	printf("square_root(%d) is called\n", argp->num);

	return &result;
}

int *
factorial_1_svc(math_input *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	int temp = 1, cnt = argp->num;
	while(cnt > 1){
		temp *= cnt;
		cnt--;
	}

	result = temp;

	return &result;
}
