/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "math_operations.h"

bool_t
xdr_math_input (XDR *xdrs, math_input *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->num))
		 return FALSE;
	return TRUE;
}
